// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhsYi5gL4cyhqcQizxUVQ3ijqUezlTEvs',
    appId: '1:743699534495:web:8710732ca037fe85bbc8aa',
    messagingSenderId: '743699534495',
    projectId: 'ecommerce-dec3e',
    authDomain: 'ecommerce-dec3e.firebaseapp.com',
    storageBucket: 'ecommerce-dec3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjIgwjCPccVjGWEyERR7PTPfR-mcHyZe8',
    appId: '1:743699534495:android:68daaad4846beadbbbc8aa',
    messagingSenderId: '743699534495',
    projectId: 'ecommerce-dec3e',
    storageBucket: 'ecommerce-dec3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh_8h5-q4pKdsmPPWP9P0sgDZDxzpSGuk',
    appId: '1:743699534495:ios:3341932b410fed19bbc8aa',
    messagingSenderId: '743699534495',
    projectId: 'ecommerce-dec3e',
    storageBucket: 'ecommerce-dec3e.appspot.com',
    iosClientId: '743699534495-u412dggicia8k7t9pga4tspmkbfcah4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.megaStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh_8h5-q4pKdsmPPWP9P0sgDZDxzpSGuk',
    appId: '1:743699534495:ios:3341932b410fed19bbc8aa',
    messagingSenderId: '743699534495',
    projectId: 'ecommerce-dec3e',
    storageBucket: 'ecommerce-dec3e.appspot.com',
    iosClientId: '743699534495-u412dggicia8k7t9pga4tspmkbfcah4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.megaStore',
  );
}
